### ISSUE TITLE
After sign the transaction from casper wallet, unable to send the transaction using putDeploy to the network

### ISSUE THREAD

**Issue by UmerMughal96143** [make-software/casper-wallet-sdk#8]
Hi i was upgrading my application from casper signer to casper wallet extension and i am getting errors while sending the signedObject to the network for execution of transfer CSPR's.

here is the some code snippet grabbed from casper wallet playground 

const handleSignDeploy = (
    accountPublicKey: string,
    deploy: DeployUtil.Deploy
  ) => {
    if (accountPublicKey) {
      const deployJson: any = DeployUtil.deployToJson(deploy);
      sign(JSON.stringify(deployJson), accountPublicKey)
        .then(async (res: any) => {
          if (res.cancelled) {
            alert('Sign cancelled');
          } else {
            const signedDeploy: any = DeployUtil.setSignature(
              deploy,
              res.signature,
              CLPublicKey.fromHex(accountPublicKey)
            );
            let validateDeploy = DeployUtil.validateDeploy(signedDeploy);
            
            
            

           // What to do for sending the signedDeploy to the test network  ?????????? 
           
           
           
           
           
            // alert('Sign successful: ' + JSON.stringify(signedDeploy, null, 2));
          }
        })
        .catch(err => {
          console.log("🚀 ~ file: index.tsx:467 ~ err:", err)
          alert('Error: ' + err);
          throw err;
        });
    }
  };
  
  unable to send the validateDeploy object to the network,
  any assistant would be helpful

**Comment by UmerMughal96143** [comment]
Is there any code snippet to send the signedDeploy to the network using casper wallet instead of casper signer.

**Comment by mrkara** [comment]
Closing for being stale for a long time. Please feel free to re-open it if needed.
