### ISSUE TITLE
Getting `No signing account` when performing an action

### ISSUE THREAD

**Issue by MessaoudAzidane** [make-software/casper-wallet-sdk#9]
### Description: 
I'm getting a `No signing account` error message whenever I try to perform an action (in the video bellow I was trying to do a Swap) .

https://user-images.githubusercontent.com/44622832/231757265-91d2967a-c844-40bc-9073-b643a9a5f90b.mov

### Details
- Extension Version: 1.2.5 (Open Beta)
- OS: MacOS
- Browser: Google Chrome
- Code that's making the request: https://github.com/Rengo-Labs/uniswap-casper-interface/blob/develop/src/commons/deploys/swap.ts

**Comment by piotrwitek** [comment]
@MessaoudAzidane please use official release that's already fixed

**Comment by Levike34** [comment]
@piotrwitek I am still getting this same error using version 1.3.2
